### ISSUE TITLE
EFR32DeviceDataProvider pointer overwritten by GenericDeviceInstanceInfoProvider

### ISSUE THREAD

**Issue by tomasz-kos** [SiliconLabs/matter#132]
### Description of the issue

I'm working in Simplicity Studio with GSDK 4.2.2 and matter extension 1.0.5. As development board I'm using Thunderboard Sense 2 and lighting over thread app. I'm playing with parameters  like product name, serial number, sw and hw version. I couldn't get it to work as expected. After investigating I found out that function SetDeviceInstanceInfoProvider() first is call with argument pointer to EFR32DeviceDataProvider (from EFR32MatterConfig::InitMatter()) which I assume is expected behaviour. But latter SetDeviceInstanceInfoProvider() is called again with argument pointer to sGenericDeviceInstanceInfoProvider. Because of that all function for providing info about product are called from GenericDeviceInstanceInfoProvider.ipp instead of EFR32DeviceDataProvider.cpp

### Steps to reproduce the issue

```bash
It is all time behaviour. To check set breakpoint in function SetDeviceInstanceInfoProvider()and check what arguments are passed.
```

### Device type(s) and network topology

Matter lighting over thread on Thunderboard Sense 2 ( confirmed also with xG24 Dev Kit - DK2601B) with Google Nest 2.

### SMG version

release_1.0.3-1.0

### Protocol(s)

Openthread

### Hardware platform(s)

Thunderboard Sense 2

### Development platform(s)

SSv5 on Windows 11

**Comment by tomasz-kos** [comment]
release_1.0.5-1.0 but I couldn't select from dropdown list

**Comment by silabs-sebastien** [comment]
Hi @tomasz-kos ,
Please note bug reports filed in this repo are only for SMG (Silabs Matter GitHub) and not for bugs related to MGE (Matter GSDK Extension) or general support requests.
Please follow [this link](https://community.silabs.com/s/topic/0TO1M000000qHZgWAM/matter?language=en_US) to open a question on the community instead for your support request concerning the Matter GSDK Extension.
