### ISSUE TITLE
Ecosystems validation suggestions

### ISSUE THREAD

**Issue by hslin224** [SiliconLabs/matter#146]
### General description of the feature

1. For Samsung Hub, Smart Things WIFI/HUB (Aeotec) is not equipped with Thread Radio. Suggest to use Samsung SmartThings Station for evaluation usage.
2. The Amazon Echo Dot is not equipped with Thread Radio. Suggest to use Amazon Echo(4th gen) for evaluation usage.

### SMG version

release_2.2.0-1.2

### Protocol(s)

Thread

### Hardware platform(s)

MG21, MG24

**Comment by lboue** [comment]
@hslin224 
Check [Silicon Labs Matter GitHub v2.3.0-1.3-beta.1](https://github.com/SiliconLabs/matter/releases/tag/v2.3.0-1.3-beta.1) release.
Samsung Hub has been added
- Hardware: Smart Things Station
- Thread: Software: 1.8.12.21
- Wi-Fi: Software: 2.3.29-7

**Comment by hslin224** [comment]
@lboue 
Great! Do you know if there're documents for test scenarios?

**Comment by lboue** [comment]
> @lboue Great! Do you know if there're documents for test scenarios?

You should ask SiliconLabs about that.

**Comment by rerasool** [comment]
Good catch. I checked with the team and the hub details used for Thread testing were missed in the release notes. This has been addressed in the latest release as mentioned by @lboue : https://github.com/SiliconLabs/matter/releases/tag/v2.3.0-1.3-beta.1

Test scenarios were also shared with @hslin224 separately.

Closing the issue, please reopen if needed, thanks.
