### ISSUE TITLE
activate.sh script fails on Raspberry Pi

### ISSUE THREAD

**Issue by below** [SiliconLabs/matter#34]
#### activate.sh script fails on Raspberry Pi
The `activate.sh` or `bootstrap.sh` scripts fail on a Raspberry Pi 4 

### Expected behavior
Scripts fail without error
### actual behavior
An Error occurs: `× Building wheel for cryptography (pyproject.toml) did not run successfully.`
### system configuration
```Linux MatterPi 5.15.0-1014-raspi #16-Ubuntu SMP PREEMPT Tue Aug 23 10:22:52 UTC 2022 armv7l armv7l armv7l GNU/Linux```
### Other Info
```
$ pip install wheel
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.37.1)
```
```
$ pip install cryptography
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (3.4.8)
```
### Full Log:
[fulllog.txt](https://github.com/SiliconLabs/matter/files/9582473/fulllog.txt)

Any help is appreciated …

**Comment by silabs-Simran** [comment]
You can follow the pre-requisite guide to set up Raspi 4. This guide will help you install library files required for Raspi4 OTBR setup: https://community.silabs.com/s/article/setup-rpi4-matter-development?language=en_US

Alternatively, you can get the latest Raspi4 Image from our SMG release: (currently 0.4.0)
https://github.com/SiliconLabs/matter/blob/release_0.4.0/docs/silabs/thread/RASPI_IMG.md

**Comment by silabs-Simran** [comment]
Closing it.

**Comment by silabs-Simran** [comment]
Closing it.
