### ISSUE TITLE
ota failed with siliconlabs efr32mg board-brd4187c

### ISSUE THREAD

**Issue by iot-lorawan** [SiliconLabs/matter#41]
#### Problem
Hi,
    I test fota with efr32mg24 in brd4187c according the url https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/silabs_efr32_software_update.md, but the efr32mg24 node always fail in find the ota-provider.

<what's wrong or missing, please include any applicable:
 * expected behavior
 * ------ota success
 * actual behavior
 * ------cannot start ota process in device find
 * 
 * steps to reproduce
 * ----follow the url  https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/silabs_efr32_software_update.md  and use the prebuild  bootloaderfile
 * 
 * system configuration
 * screenshots, images, logs, etc.
 >

<detail> [DMG] Received command for Endpoint=1 Cluster=0x0000_0006 Command=0x0000_0002
<info  > [ZCL] On/Off set value: 1 2
<info  > [ZCL] Toggle on/off from 1 to 0
<info  > [ZCL] Off Command - OnTime :  0
<detail> [DMG] Endpoint 1, Cluster 0x0000_0006 update version to 3d3f63b9
<info  > [ZCL] Cluster callback: 0x0000_0006
<detail> [DMG] Endpoint 1, Cluster 0x0000_0006 update version to 3d3f63ba
<info  > [ZCL] Cluster callback: 0x0000_0006
<efr32 > Turning light Off
<efr32 > Light OFF
<detail> [IN] UDP Message Received packet nb : 14 SrcAddr : fd92:c8ce:db14:1:9477:e3af:d9f2:5bf7[40582] DestAddr : fd92:c8ce:db14:1:2a93:e1f0:bac1:c15a[5540] Payload <detail> [DMG] Command handler moving to [ Preparing]
<detail> [DMG] Command handler moving to [AddingComm]
<detail> [DMG] Command handler moving to [AddedComma]
<detail> [DMG] Decreasing reference count for CommandHandler, remaining 0
<detail> [EM] Piggybacking Ack for MessageCounter:2446002 on exchange: 37755r
<info  > [IN] Prepared secure message 0x2001edc4 to 0x000000000001B669 (1)  of type 0x9 and protocolId (0, 1) on exchange 37755r with MessageCounter:56906613.
<info  > [IN] Sending encrypted msg 0x2001edc4 with MessageCounter:56906613 to 0x000000000001B669 (1) at monotonic time: 000000000000935B msec
<detail> [DMG] Command handler moving to [CommandSen]
<detail> [DMG] Command handler moving to [AwaitingDe]
<info  > [EM] Received message of type 0x10 with protocolId (0, 0) and MessageCounter:169266623 on excha<detail> [IN] UDP Message Received packet nb : 15 SrcAddr : fd92:c8ce:db14:1:9477:e3af:d9f2:5bf7[40582] DestAddr : fd92:c8ce:db14:1:2a93:e1f0:bac1:c15a[5540] Payload Length 34
<info  > [EM] Received message of type 0x10 with protocolId (0, 0) and MessageCounter:2446003 on exchange 37755r
<detail> [EM] Found matching exchange: 37755r, Delegate: 0
<detail> [EM] Rxd Ack; Removing MessageCounter:56906613 from Retrans Table on exchange 37755r
<detail> [EM] Removed CHIP MessageCounter:56906613 from RetransTable on exchange 37755r
<detail> [IN] UDP Message Received packet nb : 16 SrcAddr : fd92:c8ce:db14:1:9477:e3af:d9f2:5bf7[59312] DestAddr : fd92:c8ce:db14:1:2a93:e1f0:bac1:c15a[5540] Payload Length 177
<info  > [EM] Received message of type 0x30 with protocolId (0, 0) and MessageCounter:158534876 on exchange 44080r
<detail> [EM] Handling via exchange: 44080r, Delegate: 0x2001d9f8
<info  > [IN] CASE Server received Sigma1 message. Starting handshake. EC 0x2001e738
<info  > [IN] CASE Server disabling CASE session setups
<detail> [EM] Sending Standalone Ack for MessageCounter:158534876 on exchange 44080r
<info  > [IN] Prepared unauthenticated message 0x200166f4 to 0x0000000000000000 (0)  of type 0x10 and protocolId (0, 0) on exchange 44080r with MessageCounter:30756970.
<info  > [IN] Sending unauthenticated msg 0x200166f4 with MessageCounter:30756970 to 0x0000000000000000 at monotonic time: 0000000000012BAD msec
<detail> [EM] Flushed pending ack for MessageCounter:158534876 on exchange 44080r
<info  > [SC] Received Sigma1 msg
<detail> [IN] UDP Message Received packet nb : 17 SrcAddr : fd92:c8ce:db14:1:9477:e3af:d9f2:5bf7[59312] DestAddr : fd92:c8ce:db14:1:2a93:e1f0:bac1:c15a[5540] Payload Length 598
<info  > [EM] Received message of type 0x32 with protocolId (0, 0) and MessageCounter:158534877 on exchange 44080r
<detail> [EM] Found matching exchange: 44080r, Delegate: 0x2001da14
<detail> [EM] Rxd Ack; Removing MessageCounter:30756971 from Retrans Table on exchange 44080r
<detail> [EM] Removed CHIP MessageCounter:30756971 from RetransTable on exchange 44080r
<detail> [EM] Sending Standalone Ack for MessageCounter:158534877 on exchange 44080r
<info  > [IN] Prepared unauthenticated message 0x200166e4 to 0x0000000000000000 (0)  of type 0x10 and protocolId (0, 0) on exchange 44080r with MessageCounter:30756972.
<info  > [IN] Sending unauthenticated msg 0x200166e4 with MessageCounter:30756972 to 0x0000000000000000 at monotonic time: 0000000000012D44 msec
<detail> [EM] Flushed pending ack for MessageCounter:158534877 on exchange<detail> [IN] UDP Message Received packet nb : 18 SrcAddr : fd92:c8ce:db14:1:9477:e3af:d9f2:5bf7[59312] DestAddr : fd92:c8ce:db14:1:2a93:e1f0:bac1:c15a[5540] Payload Length 71
<info  > [EM] Received message of type 0x8 with protocolId (0, 1) and MessageCounter:101179939 on exchange 44081r
<detail> [EM] Handling via exchange: 44081r, Delegate: 0x2000a894
<detail> [DMG] Received command for Endpoint=0 Cluster=0x0000_002A Command=0x0000_0000
<info  > [SWU] OTA Requestor received AnnounceOTAProvider
<detail> [SWU]   FabricIndex: 1
<detail> [SWU]   ProviderNodeID: 0x0000000000000001
<detail> [SWU]   VendorID: 0x0
<detail> [SWU]   AnnouncementReason: 0
<detail> [SWU]   Endpoint: 0
<detail> [DMG] Command handler moving to [ Preparing]
<detail> [DMG] Command handler moving to [AddingComm]
<detail> [DMG] Command handler moving to [AddedComma]
<detail> [DMG] Decreasing reference count for CommandHandler, remaining 0
<detail> [EM] Piggybacking Ack for MessageCounter:101179939 on exchange: 44081r
<info  ><detail> [IN] UDP Message Received packet nb : 19 SrcAddr : fd92:c8ce:db14:1:9477:e3af:d9f2:5bf7[59312] DestAddr : fd92:c8ce:db14:1:2a93:e1f0:bac1:c15a[5540] Payload Length 26
<info  > [EM] Received message of type 0x10 with protocolId (0, 0) and MessageCounter:158534878 on exchange 44080r
<detail> [EM] Found matching exchange: 44080r, Delegate: 0
<detail> [EM] Rxd Ack; Removing MessageCounter:30756973 from Retrans Table on exchange 44080r
<detail> [EM] Removed CHIP MessageCounter:30756973 from RetransTable on exchange 44080r
<detail> [IN] UDP Message Received packet nb : 20 SrcAddr : fd92:c8ce:db14:1:9477:e3af:d9f2:5bf7[59312] DestAddr : fd92:c8ce:db14:1:2a93:e1f0:bac1:c15a[5540] Payload Length 34
<info  > [EM] Received message of type 0x10 with protocolId (0, 0) and MessageCounter:101179940 on exchange 44081r
<detail> [EM] Found matching exchange: 44081r, Delegate: 0
<detail> [EM] Rxd Ack; Removing MessageCounter:10318284 from Retrans Table on exchange 44081r
<detail> [EM] Removed CHIP MessageCoun<info  > [DIS] Checking node lookup status after 200 ms
<info  > [DIS] Node ID resolved for 03B67BB7E69B873D:0000000000000001
<detail> [DIS]   Hostname: DCA632AB97FF0000
<detail> [DIS]   IP Address #1: 0:0:0:0:0:0:0:0
<detail> [DIS]   Port: 5540
<detail> [DIS]   Mrp Interval idle: 5000 ms
<detail> [DIS]   Mrp Interval active: 2000 ms
<detail> [DIS]   TCP Supported: 1
<error > [DIS] Skipping IPv4 address during operational resolve.
<info  > [DIS] Checking node lookup status after 5209 ms
<info  > [DL] _OnPlatformEvent default:  event->Type = 32777
<detail> [DL] OpenThread State Changed (Flags: 0x00000064)
<detail> [DL]    Device Role: ROUTER
<info  > [DIS] Checking node lookup status after 15000 ms
<error > [DIS] OperationalSessionSetup[1:0000000000000001]: operational discovery failed: 32
<error > [SWU] Failed to connect to node 0x0000000000000001: 32
<detail> [EVL] LogEvent event number: 0x0000000000040004 priority: 1, endpoint id:  0x0 cluster id: 0x0000_002A event id: 0x2 Epoch timestamp: 0x000000DC6AD11448
<detail> [DMG] Endpoint 0, Cluster 0x0000_002A update version to 9e76efe9
<info  > [ZCL] Cluster callback: 0x0000_002A
<detail> [EVL] LogEvent event number: 0x0000000000040005 priority: 1, endpoint id:  0x0 cluster id: 0x0000_002A event id: 0x0 Epoch timestamp: 0x000000DC6AD11448
<info  > [SWU] Unknown idle state reason so set the periodic timer for a next attempt
<info  > [SWU] Stopping the watchdog timer
<info  > [SWU] Starting the periodic query timer, timeout: 86400 seconds

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by silabs-sebastien** [comment]
@iot-lorawan Have you tried this again with the [newest release (0.4.0)](https://github.com/SiliconLabs/matter/releases/tag/v0.4.0)?

**Comment by silabs-sebastien** [comment]
If you need further assistance, please open a ticket on the community [here](https://community.silabs.com/s/topic/0TO1M000000qHZgWAM/matter?language=en_US).
