### ISSUE TITLE
How to use linux chiptool and OTBR in linux system instead of Raspberry Pi

### ISSUE THREAD

**Issue by VivekPalle** [SiliconLabs/matter#46]
Hi,

We want to run OTBR and chiptool (Matter Hub) in the linux system instead of Raspberry. Can you please share the procedure available to do this.
As we found there are procedures available for Virtual Box and Raspberry Pi, but how can I use my Linux system to run the Matter Hub (Chiptool and OTBR) to commission and control the MAD (Matter-Thead) end device.
I am also having EFR32 USB STICK to run the RCP code.

Please help with the possibilities and procedures that meet above requirement.

**Comment by silabs-sebastien** [comment]
For support requests, please ask your questions in [Silabs Matter Community](https://community.silabs.com/s/topic/0TO1M000000qHZgWAM/matter?language=en_US).
