### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Leo2442926161** [SiliconLabs/matter#55]
### Description of the issue

I am trying to flash DAC and CD to efr32, I followed https://github.com/SiliconLabs/matter/blob/release_0.4.0/silabs_examples/credentials but the build is failed, could you help me? thank you.

python3 ./creds.py -p /dev/ttyACM1 -S 59406895 -B brd4186a -C pai_cert.pem -K pai_priv.pem -D cd.bin

**Linking build/debug/device-creds.out
/home/leo/armGNU/gnu/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld:/home/leo/matter/connectedhomeip/third_party/silabs/gecko_sdk//platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a: file format not recognized; treating as linker script
/home/leo/armGNU/gnu/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld:/home/leo/matter/connectedhomeip/third_party/silabs/gecko_sdk//platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a:1: syntax error
collect2: error: ld returned 1 exit status
make: *** [device-creds.Makefile:156: build/debug/device-creds.out] Error 1
make: Leaving directory '/home/leo/matter/connectedhomeip/silabs_examples/credentials/device/brd4186a'
ERROR: 2
**

### Steps to reproduce the issue

```bash
execute: python3 ./creds.py -p /dev/ttyACM1 -S 59406895 -B brd4186a -C pai_cert.pem -K pai_priv.pem -D cd.bin
```

### Device type(s) and network topology

Ubuntu 20.04

### SMG version

release_0.4.0

### Protocol(s)

Openthread

### Hardware platform(s)

MG24

**Comment by silabs-sebastien** [comment]
For support requests, please ask your questions in [Silabs Matter Community](https://community.silabs.com/s/topic/0TO1M000000qHZgWAM/matter?language=en_US).

**Comment by Leo2442926161** [comment]
thank you,have fixed it.
