### ISSUE TITLE
build failed when i use release_0.2.0 to release_0.3.0

### ISSUE THREAD

**Issue by cosmosstone** [SiliconLabs/matter#61]
### Description of the issue

I used the cmd

 ./scripts/examples/gn_efr32_example.sh ./examples/light-switch-app/efr32/ ./out/light-switch-app BRD4186A
 in  [release_0.2.0] . Is ok.

then i try to use this cmd in [release_0.3.0]

git branch -a
git checkout -b release_0.3.0 origin/release_0.3.0

git checkout .

and use this cmd ,An error was reported.

ERROR at //third_party/connectedhomeip/third_party/openthread/BUILD.gn:27:23: Unable to load "/home/fake/Documents/mattersdk/matter/examples/light-switch-app/efr32/third_party/connectedhomeip/third_party/openthread/ot-efr32/openthread/BUILD.gn".
      public_deps = [ "${openthread_root}:libopenthread-ftd" ]
                      ^-------------------------------------

How to get the BUILD.gn?

### Steps to reproduce the issue

```bash
git branch -a
release_0.2.0 change to release_0.3.0
and use cmd 

./scripts/examples/gn_efr32_example.sh ./examples/light-switch-app/efr32/ ./out/light-switch-app BRD4186A
or use 
./scripts/examples/gn_efr32_example.sh ./examples/light-switch-app/efr32/ ./out/light-switch-app BRD4186C



expected behavior
When we use the cmd , it should compile successfully.

actual behavior
It displays an "Unable to load  BUILD.gn " error.
```

### Device type(s) and network topology

Ubunto 20.04

### SMG version

release_0.3.0

### Protocol(s)

Openthread

### Hardware platform(s)

BRD4186C

### Captured data or logs

root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# git log
commit efb8612d0f97d8c8062a67e44b7276c04074bec5 (HEAD -> release_0.2.0, tag: v0.2.0, origin/release_0.2.0, doubleboard)
Author: Hussein Elsherbini <Hussein.Elsherbini@silabs.com>
Date:   Wed Aug 17 17:58:36 2022 +0000

    Pull request #49: fixed bugs in windows setup script, and modified other related scripts
    
    Merge in WMN_TOOLS/matter from windows_support to silabs
    
    Squashed commit of the following:
    
    commit 637199bc57b72f6d0c38ac5e5fbc369313ab79d1
    Author: Hussein Elsherbini <Hussein.Elsherbini@silabs.com>
    Date:   Wed Aug 17 13:30:45 2022 -0400
    
        fixed bugs in windows setup script, and modified other related scripts

commit d49b6f1b05c68337228e7632cb78131e3bc7e64e
Author: Junior Martinez <Junior.Martinez@silabs.com>
Date:   Wed Aug 17 13:20:25 2022 +0000

    Pull request #45: [EFR32] Destroy PSA key_id if exists. (#21920)
    
    Merge in WMN_TOOLS/matter from fix_psa_err-139 to silabs
    
    Squashed commit of the following:
...skipping...
commit efb8612d0f97d8c8062a67e44b7276c04074bec5 (HEAD -> release_0.2.0, tag: v0.2.0, origin/release_0.2.0, doubleboard)
Author: Hussein Elsherbini <Hussein.Elsherbini@silabs.com>
Date:   Wed Aug 17 17:58:36 2022 +0000

    Pull request #49: fixed bugs in windows setup script, and modified other related scripts
    
    Merge in WMN_TOOLS/matter from windows_support to silabs
    
    Squashed commit of the following:
    
    commit 637199bc57b72f6d0c38ac5e5fbc369313ab79d1
    Author: Hussein Elsherbini <Hussein.Elsherbini@silabs.com>
    Date:   Wed Aug 17 13:30:45 2022 -0400
    
        fixed bugs in windows setup script, and modified other related scripts

commit d49b6f1b05c68337228e7632cb78131e3bc7e64e
Author: Junior Martinez <Junior.Martinez@silabs.com>
Date:   Wed Aug 17 13:20:25 2022 +0000

    Pull request #45: [EFR32] Destroy PSA key_id if exists. (#21920)
    
    Merge in WMN_TOOLS/matter from fix_psa_err-139 to silabs
    
    Squashed commit of the following:
    
    commit 8514ea0275dce67c7ed0d8284b7def687666cf67
    Author: Ricardo Casallas <77841255+rcasallas-silabs@users.noreply.github.com>
    Date:   Tue Aug 16 16:00:48 2022 -0400
    
        [EFR32] Destroy PSA key_id if exists. (#21920)
    
        * [EFR32] Recover from PSA keygen error.
    
        * [EFR32] Destroy existing PSA key_id before re-using it.

commit 1b1268cd61805ba2b9cd54d125cde6901cd7dc2d
Author: Ezra Hale <ezra.hale@silabs.com>
Date:   Wed Aug 17 13:17:46 2022 +0000

    Pull request #44: updated links on artifacts page and info on using bootloader images
    
    Merge in WMN_TOOLS/matter from v0.2.0_release_doc_update to silabs
    
    Squashed commit of the following:
    
    commit eeffbad47a6e0bd59251d50b28904a69d557ffc5
    Author: Rehan Rasool <Rehan.Rasool@silabs.com>
    Date:   Tue Aug 16 18:24:53 2022 -0400
    
        Fix typo
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# git branch -a
  doubleboard
* release_0.2.0
  release_0.3.0
  remotes/origin/interop_testing_te9
  remotes/origin/master
  remotes/origin/release_0.1.0
  remotes/origin/release_0.2.0
  remotes/origin/release_0.3.0
  remotes/origin/release_0.4.0
  remotes/origin/release_1.0.0
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# git checkout release_0.3.0
warning: unable to rmdir 'third_party/cyw30739_sdk/repos/30739A0': Directory not empty
warning: unable to rmdir 'third_party/cyw30739_sdk/repos/CYW930739M2EVB-01': Directory not empty
warning: unable to rmdir 'third_party/cyw30739_sdk/repos/btsdk-include': Directory not empty
warning: unable to rmdir 'third_party/cyw30739_sdk/repos/btsdk-tools': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/TARGET_CY8CKIT-062S2-43012': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/abstraction-rtos': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/anycloud-ota': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/bluetooth-freertos': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/btstack': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/clib-support': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/connectivity-utilities': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/core-lib': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/core-make': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/freertos': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/kv-store': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/lwip': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/mbedtls': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/mtb-hal-cat1': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/mtb-pdl-cat1': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/psoc6cm0p': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/recipe-make-cat1a': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/retarget-io': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/secure-sockets': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/serial-flash': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/whd-bsp-integration': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/wifi-connection-manager': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/wifi-host-driver': Directory not empty
warning: unable to rmdir 'third_party/p6/p6_sdk/libs/wifi-mw-core': Directory not empty
M	third_party/bouffalolab/bl602_sdk/repo
M	third_party/openthread/ot-efr32
M	third_party/openthread/ot-ifx
M	third_party/silabs/gecko_sdk
M	third_party/silabs/matter_support
M	third_party/ti_simplelink_sdk/repo_cc32xx
M	third_party/zap/repo
Switched to branch 'release_0.3.0'
Your branch is up to date with 'origin/release_0.3.0'.
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# git branch
  doubleboard
  release_0.2.0
* release_0.3.0
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# git branch -a
  doubleboard
  release_0.2.0
* release_0.3.0
  remotes/origin/interop_testing_te9
  remotes/origin/master
  remotes/origin/release_0.1.0
  remotes/origin/release_0.2.0
  remotes/origin/release_0.3.0
  remotes/origin/release_0.4.0
  remotes/origin/release_1.0.0
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# git checkout HEAD
M	third_party/bouffalolab/bl602_sdk/repo
M	third_party/openthread/ot-efr32
M	third_party/openthread/ot-ifx
M	third_party/silabs/gecko_sdk
M	third_party/silabs/matter_support
M	third_party/ti_simplelink_sdk/repo_cc32xx
M	third_party/zap/repo
Your branch is up to date with 'origin/release_0.3.0'.
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# git checkout .
Updated 0 paths from the index
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# 
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# ./scripts/examples/gn_efr32_example.sh ./examples/light-switch-app/efr32/ ./out/light-switch-app BRD4186A
Using default path for Matter root

  WELCOME TO...

         █
         █
     ▄   █   ▄                                █     █
     ▀▀█████▀▀      ▄▀▀▀▄ ▄▀▀▀▄    ▄▀▀▀▀▄█  ▀▀█▀▀▀▀▀█▀▀   ▄▀▀▀▀▄    ▄▀▀
   ▀█▄       ▄█▀   █     █     █  █      █    █     █    █▄▄▄▄▄▄█  █   
     ▀█▄   ▄█▀     █     █     █  █      █    █     █    █         █   
  ▄██▀▀█   █▀▀██▄  █     █     █   ▀▄▄▄▄▀█    ▀▄▄   ▀▄▄   ▀▄▄▄▄▀   █   
 ▀▀    █   █    ▀▀

  ACTIVATOR! This sets your shell environment variables.

Activating environment (setting environment variables):

  Setting environment variables for CIPD package manager...done
  Setting environment variables for Python environment.....done
  Setting environment variables for pw packages............skipped
  Setting environment variables for Host tools.............done

Checking the environment:

20221104 11:37:13 WRN Current uname (5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64) does not match Bootstrap uname (5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64), you may need to rerun bootstrap on this system
20221104 11:37:13 INF Environment passes all checks!

Environment looks good, you are ready to go!

+ env
SHELL=/bin/bash
COLORTERM=truecolor
SUDO_GID=1000
LC_ADDRESS=zh_CN.UTF-8
LC_NAME=zh_CN.UTF-8
PW_PROJECT_ROOT=/home/fake/Documents/mattersdk/matter
SUDO_COMMAND=/usr/bin/su
LC_MONETARY=zh_CN.UTF-8
SUDO_USER=fake
PWD=/home/fake/Documents/mattersdk/matter
LOGNAME=root
XAUTHORITY=/run/user/1000/gdm/Xauthority
PW_ROOT=/home/fake/Documents/mattersdk/matter/third_party/pigweed/repo
HOME=/root
LC_PAPER=zh_CN.UTF-8
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
VIRTUAL_ENV=/home/fake/Documents/mattersdk/matter/.environment/pigweed-venv
PW_PYTHON_CIPD_INSTALL_DIR=/home/fake/Documents/mattersdk/matter/.environment/cipd/packages/python
_PW_ROSETTA=0
LESSCLOSE=/usr/bin/lesspipe %s %s
TERM=xterm-256color
LC_IDENTIFICATION=zh_CN.UTF-8
LESSOPEN=| /usr/bin/lesspipe %s
USER=root
DISPLAY=:0
SHLVL=2
LC_TELEPHONE=zh_CN.UTF-8
PW_PACKAGE_ROOT=/home/fake/Documents/mattersdk/matter/.environment/packages
LC_MEASUREMENT=zh_CN.UTF-8
_PW_ENVIRONMENT_CONFIG_FILE=/home/fake/Documents/mattersdk/matter/scripts/environment.json
_PW_ACTUAL_ENVIRONMENT_ROOT=/home/fake/Documents/mattersdk/matter/.environment
PW_BRANDING_BANNER=/home/fake/Documents/mattersdk/matter/scripts/matter_banner.txt
PW_ARM_CIPD_INSTALL_DIR=/home/fake/Documents/mattersdk/matter/.environment/cipd/packages/arm
LC_TIME=zh_CN.UTF-8
PATH=/home/fake/Documents/mattersdk/matter/third_party/pigweed/repo/out/host/host_tools:/home/fake/Documents/mattersdk/matter/.environment/pigweed-venv/bin:/home/fake/Documents/mattersdk/matter/.environment/cipd/packages/python/bin:/home/fake/Documents/mattersdk/matter/.environment/cipd/packages/python:/home/fake/Documents/mattersdk/matter/.environment/cipd/packages/pigweed/bin:/home/fake/Documents/mattersdk/matter/.environment/cipd/packages/pigweed:/home/fake/Documents/mattersdk/matter/.environment/cipd/packages/arm/bin:/home/fake/Documents/mattersdk/matter/.environment/cipd/packages/arm:/home/fake/Documents/mattersdk/matter/.environment/cipd:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
SUDO_UID=1000
MAIL=/var/mail/root
PW_PIGWEED_CIPD_INSTALL_DIR=/home/fake/Documents/mattersdk/matter/.environment/cipd/packages/pigweed
LC_NUMERIC=zh_CN.UTF-8
_=/usr/bin/env
+ USE_WIFI=false
+ SILABS_THREAD_TARGET='"../silabs:ot-efr32-cert"'
+ USAGE='./scripts/examples/gn_efr32_example.sh <AppRootFolder> <outputFolder> <efr32_board_name> [<Build options>]'
+ '[' 3 == 0 ']'
+ '[' 3 -lt 2 ']'
+ ROOT=./examples/light-switch-app/efr32/
+ OUTDIR=./out/light-switch-app
+ '[' 3 -gt 2 ']'
+ EFR32_BOARD=BRD4186A
+ shift
+ shift
+ shift
+ '[' 0 -gt 0 ']'
+ '[' -z BRD4186A ']'
+ BUILD_DIR=./out/light-switch-app/BRD4186A
+ echo BUILD_DIR=./out/light-switch-app/BRD4186A
BUILD_DIR=./out/light-switch-app/BRD4186A
+ '[' false == true ']'
+ '[' -z '' ']'
+ gn gen --check --fail-on-unused-args --export-compile-commands --root=./examples/light-switch-app/efr32/ '--args=efr32_board="BRD4186A"' ./out/light-switch-app/BRD4186A
RevA is deprecated, We suggest using BRD4186C (rev C)
ERROR at //third_party/connectedhomeip/third_party/openthread/BUILD.gn:27:23: Unable to load "/home/fake/Documents/mattersdk/matter/examples/light-switch-app/efr32/third_party/connectedhomeip/third_party/openthread/ot-efr32/openthread/BUILD.gn".
      public_deps = [ "${openthread_root}:libopenthread-ftd" ]
                      ^-------------------------------------
root@fake-virtual-machine:/home/fake/Documents/mattersdk/matter# ./scripts/examples/gn_efr32_example.sh ./examples/light-switch-app/efr32/ ./out/light-switch-app BRD4186C
Using default path for Matter root

  WELCOME TO...

**Comment by silabs-sebastien** [comment]
Hi @cosmosstone ,
Did you try this again with the newest release, 1.0.0? If not, please do and let us know if you get a different result with the latest release.
