### ISSUE TITLE
silabs_examples/sl-newLight build failed

### ISSUE THREAD

**Issue by bytespectrumllp** [SiliconLabs/matter#70]
### Description of the issue

While builing the sl-newLight example for board BRD2601B
build failed with following error.
![image](https://user-images.githubusercontent.com/96565845/203785940-713bb141-7c47-4dc4-ac05-e7f143e9f64a.png)

System: Ubuntu 20.04.4 LTS: 8GB RAM 64 bit core i5 7th gen.

Attaching the log file as well.

### Steps to reproduce the issue

```bash
1. clone Release 1.0.0
2. cd matter
3. export SILABS_BOARD=BRD2601B
4. Also tried with > export EFR32_BOARD=BRD2601B
5. source scripts/activate.sh
6. ./scripts/examples/gn_efr32_example.sh ./silabs_examples/sl-newLight/efr32 ./out/sl-newLight
```

### Device type(s) and network topology

EFR32MG24: Thunderboard sense devkit BRD2601B Matter end device

### SMG version

release_1.0.0

### Protocol(s)

Openthread, Wifi, Bluetooth

### Hardware platform(s)

xG24 Devkit Thunderboard sense: BRD2601B

### Captured data or logs

[err.log](https://github.com/SiliconLabs/matter/files/10084677/err.log)

![image](https://user-images.githubusercontent.com/96565845/203788385-e7d8dfb4-e38c-4ddc-b560-a850cf767c0c.png)

**Comment by Chandrajadeja** [comment]
It's been 7 days since I posted the issue, it is blocker one. Please help me to resolve this

**Comment by grobasoz** [comment]
So it seems the ports and pins are hardwired in _led_widget_rgb.cpp_ and don't reference the actual board layout - even though the BRD2601B is specifically referenced (as RGB) in the build.gn file - see RGB_LED_ENABLED.

The appropriate include file (eg brd2610b/sl_simple_rgb_pwm_led_rgb_led0_config.h) should be included in the build.gn based on the silabs_board (ie - if RGB exists) and pins correctly mapped.

**Comment by eos1d3** [comment]
No need to hope Silicon Labs will help there. They are irresponsive. 

Just follow https://developers.home.google.com/matter/vendors/silicon-labs

And I just tested BRD4161A, BRD2703A and your BRD2601B, all built well. No error is found.

I do not have any board right now. Just build all these. So I am considering to get some boards to test later.

**Comment by grobasoz** [comment]
You can now build Matter projects in Simplicity Studio.

**Comment by eos1d3** [comment]
@grobasoz Did I miss something? I installed and found only 1 Matter example.

**Comment by grobasoz** [comment]
I think there are 6 examples, standard lights, switches, locks etc...
What did you install?

**Comment by eos1d3** [comment]
It is SimplicityStudio-5 Mac version. After installation, I search "matter" in example and cannot find others.

It did install a lot of libraries. Any additional tools to install?

**Comment by grobasoz** [comment]
I haven't tried on the Mac, I'll do so when I get to work this morning... 6:49 am here at the moment...

**Comment by grobasoz** [comment]
Matter samples are on Mac as well... eg for BRD4166A (Thunderboard Sense 2)

![image](https://user-images.githubusercontent.com/5369713/211412218-008b24ad-2f63-482a-be49-2636e0fb81d2.png)

![image](https://user-images.githubusercontent.com/5369713/211412296-98c7802e-a3bc-41cd-a7aa-cdd4908c887e.png)

**Comment by eos1d3** [comment]
Great thanks!! I will try again.

I tried SimplicityStudio-5 on macOS Monterey earlier without installation issue. I am current installing it on Ventura, it always quit after "Welcome to Simplicity Studio" screen. I tried many times and got the same problem.  Is this a known issue? 

I can switch back to Monterey and test later.

**Comment by grobasoz** [comment]
I'm using Monterey - on the [Silabs forum](https://community.silabs.com/s/question/0D58Y00009Zf4vJSAR/when-will-simplicity-studio-5-be-compatible-with-macos-13) others have had issue with Ventura though...

**Comment by eos1d3** [comment]
Just checked the forum, I am getting the same problem. I have to down grade to Monterey to test. Thanks!

**Comment by eos1d3** [comment]
Actually there are a lot more Matter examples for different boards. Using BRD2703A I found 11 examples.

**Comment by grobasoz** [comment]
> Actually there are a lot more Matter examples for different boards. Using BRD2703A I found 11 examples.

Thanks for that info! I never really checked boards I don't have here...

Actually I have had to move back to the GitHub release (1.0.2) as the Simplicity versions don't fully work for some reason?
See [here](https://community.silabs.com/s/question/0D58Y00009iPMmySAG/printing-qr-codes?language=en_US)...

Managed to get a lighting-app built and connected to an Apple HomePod Mini via Eve/Home.

How's that for "confusing" an already complicated development!?!

**Comment by silabs-sebastien** [comment]
Since the original poster is not involved in this issue, the building of this app/board combination is reported as working with the latest SMG and the conversation has moved on to other topics, this issue will now be closed.

If you think you found a bug with using the SMG, please [open a new issue](https://github.com/SiliconLabs/matter/issues/new/choose). If you have any other support requests, please [create a post on our community](https://community.silabs.com/s/topic/0TO1M000000qHZgWAM/matter?language=en_US).
